# Media Directories
TV="/mnt/PIHDD/media/shows"
MOVIES="/mnt/PIHDD/media/movies"
MEDIA="/mnt/PIHDD/media"
TEMP="/mnt/PIHDD/temp"

# Config directories (on server)
PLEX_CONFIG="/home/pi/plex"
SABNZB_CONFIG="/home/pi/sabnzb"
SICKBEARD_CONFIG="/home/pi/sickbeard"

# Used for this setup (temp)
INIT="/home/pi/init/configs"
SCRIPTS="/home/pi/init/scripts"